<?php

namespace View;

abstract class ViewAbstract extends \Slim\View {
    public $_name;
    public $_template;
    public $_data;

    public function __construct()
    {
        parent::__construct();
    }

    public function setName($name){
        $this->_name = $name;
        return $this;
    }

    public function getName(){
        return $this->_name;
    }

    public function setTemplate($template){
        $template = str_replace('/', '\\', $template);
        $app = \App::getInstance();
        $this->templatesDirectory = $this->getTemplatesDirectory();
        if(!is_file($this->getTemplatePathname($template))){
            $this->templatesDirectory = $app->config('templates.path');
            $this->setTemplatesDirectory('app'.DS.'View'.DS.$this->templatesDirectory);
        }
        $this->_template = $template;
        return $this;
    }

    public function getTemplatesDirectory()
    {
        $app = \App::getInstance();
        if(!$this->templatesDirectory && !$app->config('templates.path')){
            return 'web'.DS.'template';
        }elseif($this->templatesDirectory){
            return $this->templatesDirectory;
        }else{
            return $app->config('templates.path');
        }
    }

    public function getConfigTemplageDirectory(){
        $app = \App::getInstance();
        return $app->config('templates.path');
    }

    public function getTemplatePathname($file)
    {
        if($this->_template){
            return BP.DS.parent::getTemplatePathname($this->_template);
        }
        return BP.DS.parent::getTemplatePathname($file); // TODO: Change the autogenerated stub
    }


    public function display($template = null, $data = null)
    {
        if($template){
           $this->setTemplate($template);
        }
        parent::display($this->_template, $data); // TODO: Change the autogenerated stub
    }

    /**
     * get display html
     * @param null $template
     * @param null $data
     * @return string
     */
    public function fetch($template = null, $data = null)
    {
        if($template){
            $this->_template = $template;
        }
        if(!$this->_template){
            $this->setTemplate(strtolower($this->_getPathDir()).'.html');
        }
        if($data){
            $this->_data = $data;
        }
        return $this->toHtml();// TODO: Change the autogenerated stub
    }

    public function toHtml(){
        $beforeHtml = $this->_beforeToHtml();
        if(is_string($beforeHtml) && $beforeHtml != ''){
            return $beforeHtml;
        }
        return parent::fetch($this->getTemplatePathname($this->_template), $this->_data);
    }

    protected function _beforeToHtml(){

    }

    //get view path class dir
    protected function _getPathDir(){
        $basePath = BP;
        $reflector = new \ReflectionClass(get_class($this));
        $curFile = $reflector->getFileName();
        $curPath = dirname($curFile).DS.basename($curFile, '.php');
        return trim(str_replace($basePath.DS.'app'.DS.'View', '', $curPath), DS);
    }

    public function getUrl($path = '', $params = array()){
        return \App::getInstance()->getUrl($path, $params);
    }
}


