<?php

//Middleware
class App extends \Slim\Slim {

    protected $session;
    protected $connection = array(); // \Model\Database\Connection cached

    public function __construct(array $userSettings)
    {
        parent::__construct($userSettings);
    }

    public function render($template = '', $data = array(), $status = null)
    {
        parent::render($template, $data, $status); // TODO: Change the autogenerated stub
    }

    public function setSession($session){
        $this->session = $session;
        return $this;
    }

    public function getSession(){
        if($this->session){
            return $this->session;
        }
        return false;
    }

    public function getConnection($cache_key){
        if($cache_key){
            if(!isset($this->connection[$cache_key]) && $cache_key != ''){
                $this->connection[$cache_key] = new \Model\Database\Connection();
            }
            return $this->connection[$cache_key];
        }
        return new \Model\Database\Connection();
    }


    /**
     * get url with url host
     * View object also call this method
     *
     * @param string $path
     * @param array $params
     * @return string
     */
    public function getUrl($path = '', $params = array()){
        $is_secure = false;
        if(isset($params['_secure'])){
            if($params['_secure'] == '1' || $params['_secure'] == true){
                $is_secure = true;
            }
            unset($params['_secure']);
        }

        $path = ltrim($path, '/');
        $pars = '';
        foreach ($params as $name => $value) {
            $pars = $name.'='.$value.'&';
        }
        $pars = trim($pars, '&');
        if($pars != '') $pars = '?'.$pars;

        return trim($this->getBaseUrl($is_secure), '/').'/'.$path.$pars;
    }

    public function getBaseUrl($is_secure = false){
        if(!$is_secure && $this->config('base_url')){
            return $this->config('base_url');
        }elseif($is_secure && $this->config('base_url_secure')){
            return $this->config('base_url_secure');
        }
        return $this->request->getUrl().$this->request->getRootUri();
    }
}