<?php

//Middleware
class App extends \Slim\Slim {

    protected $session;
    protected $connection = array(); // \Model\Database\Connection cached

    public function __construct(array $userSettings)
    {
        parent::__construct($userSettings);
    }

    public function render($template = '', $data = array(), $status = null)
    {
        parent::render($template, $data, $status); // TODO: Change the autogenerated stub
    }

    public function setSession($session){
        $this->session = $session;
        return $this;
    }

    public function getSession(){
        if($this->session){
            return $this->session;
        }
        return false;
    }

    public function getConnection($cache_key){
        if($cache_key){
            if(!isset($this->connection[$cache_key]) && $cache_key != ''){
                $this->connection[$cache_key] = new \Model\Database\Connection();
            }
            return $this->connection[$cache_key];
        }
        return new \Model\Database\Connection();
    }
}